### ISSUE TITLE
Call to undefined function Symfony\Component\Serializer\Encoder\json_decode()

### ISSUE THREAD

**Issue by iamluc** [iamluc/docker-hostmanager#40]
When using `develop` branch

```
PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\Serializer\Encoder\json_decode() in /usr/local/src/docker-hostmanager/vendor/symfony/serializer/Encoder/JsonDecode.php:75
Stack trace:
#0 /usr/local/src/docker-hostmanager/vendor/symfony/serializer/Encoder/JsonEncoder.php(45): Symfony\Component\Serializer\Encoder\JsonDecode->decode('[{"Id":"e920246...', 'json', Array)
#1 /usr/local/src/docker-hostmanager/vendor/symfony/serializer/Encoder/ChainDecoder.php(40): Symfony\Component\Serializer\Encoder\JsonEncoder->decode('[{"Id":"e920246...', 'json', Array)
#2 /usr/local/src/docker-hostmanager/vendor/symfony/serializer/Serializer.php(280): Symfony\Component\Serializer\Encoder\ChainDecoder->decode('[{"Id":"e920246...', 'json', Array)
#3 /usr/local/src/docker-hostmanager/vendor/symfony/serializer/Serializer.php(131): Symfony\Component\Serializer\Serializer->decode('[{"Id":"e920246...', 'json', Array)
#4 /usr/local/src/docker-hostmanager/vendor/docker-php/docker-php/generated/Resource/ContainerResource.php(4 in /usr/local/src/docker-hostmanager/vendor/symfony/serializer/Encoder/JsonDecode.php on line 75
```

**Comment by iamluc** [comment]
Fixed in https://github.com/iamluc/docker-hostmanager/commit/7ead70b2ab2e12b0c2f6e559d0360248d8412ae5
